# Generated by Django 4.2.6 on 2023-11-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.IntegerField(choices=[(0, 'SUPER_ADMIN'), (1, 'USER'), (2, 'BRANCH_STAFF')], default=1),
        ),
    ]
