# Generated by Django 4.2.6 on 2023-11-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'USER ACCOUNT', 'verbose_name_plural': 'USER ACCOUNTS'},
        ),
    ]
