# Generated by Django 4.2.6 on 2023-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
    ]
