# Generated by Django 4.2.6 on 2023-12-06 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicaluseraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchCode', models.CharField(max_length=5)),
                ('BranchName', models.CharField(blank=True, max_length=255, null=True)),
                ('MainCode', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('Pan', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'USER DETAILS',
                'verbose_name_plural': 'USER DETAILS',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('BranchCode', models.CharField(max_length=5)),
                ('BranchName', models.CharField(blank=True, max_length=255, null=True)),
                ('MainCode', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('Pan', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical USER DETAILS',
                'verbose_name_plural': 'historical USER DETAILS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
