# Generated by Django 4.2.6 on 2023-12-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_historicaluseraccount_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='company',
            field=models.CharField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='company',
            field=models.CharField(default='-', max_length=254),
        ),
    ]
