# Generated by Django 4.2.6 on 2023-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyc_code', models.CharField(max_length=10)),
                ('cyc_desc', models.CharField(max_length=255)),
                ('cyc_desc_long', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CURRENCY TABLE',
                'verbose_name_plural': 'CURRENCY TABLES',
            },
        ),
        migrations.CreateModel(
            name='FCYDenoMasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterid', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('deno', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equivalentNPR', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=50)),
                ('enteredBy', models.CharField(max_length=255)),
                ('enterDate', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=255)),
                ('updateDate', models.DateTimeField()),
                ('deletedBy', models.CharField(max_length=255)),
                ('deletedDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FCY DENO MASTER TABLE',
                'verbose_name_plural': 'FCY DENO MASTER TABLES',
            },
        ),
        migrations.CreateModel(
            name='FCYExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterid', models.IntegerField()),
                ('currency_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=255)),
                ('currency_unit', models.CharField(max_length=50)),
                ('buying_rate_deno_50_or_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_rate_deno_50_or_above', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'FCY EXCHANGE RATE',
                'verbose_name_plural': 'FCY EXCHANGE RATES',
            },
        ),
        migrations.CreateModel(
            name='FCYExchangeRequestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrenceid', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('preferredBranch', models.CharField(max_length=10)),
                ('totalEquivalentNPR', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalEquivalentNPRToWords', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
                ('enteredBy', models.CharField(max_length=255)),
                ('enterDate', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=255)),
                ('updateDate', models.DateTimeField()),
                ('deletedBy', models.CharField(max_length=255)),
                ('deletedDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FCY EXCHANGE REQUEST MASTER TABLE',
                'verbose_name_plural': 'FCY EXCHANGE REQUEST MASTER TABLES',
            },
        ),
        migrations.CreateModel(
            name='FCYRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FCY RATE MASTER',
                'verbose_name_plural': 'FCY RATE MASTERS',
            },
        ),
    ]
