# Generated by Django 4.2.6 on 2023-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcyexchangerequestmaster',
            name='remarks',
            field=models.TextField(default='-'),
        ),
    ]
