# Generated by Django 4.2.6 on 2023-12-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fcyexchangerequestmaster_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcyexchangerate',
            name='buying_rate_deno_50_or_above',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fcyexchangerate',
            name='buying_rate_deno_50_or_less',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fcyexchangerate',
            name='premium_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fcyexchangerate',
            name='selling_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfcyexchangerate',
            name='buying_rate_deno_50_or_above',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfcyexchangerate',
            name='buying_rate_deno_50_or_less',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfcyexchangerate',
            name='premium_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfcyexchangerate',
            name='selling_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
