# Generated by Django 4.2.6 on 2023-12-03 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_alter_branches_branchcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBranches',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('BranchName', models.CharField(max_length=255)),
                ('BranchCode', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=20)),
                ('EmailStatus', models.CharField(max_length=20)),
                ('EmailAddress', models.CharField(max_length=255)),
                ('RegionalBranchName', models.CharField(blank=True, max_length=255, null=True)),
                ('IsEnteredBy', models.CharField(blank=True, max_length=255, null=True)),
                ('IsEnteredDate', models.CharField(blank=True, max_length=255, null=True)),
                ('IsEditedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('IsEditedDate', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical BRANCHES',
                'verbose_name_plural': 'historical BRANCHES',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
