# Generated by Django 4.2.6 on 2023-12-04 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_historicalbranches'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTellorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CyCode', models.CharField(max_length=5)),
                ('CyDesc', models.CharField(max_length=10)),
                ('MainCode', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'BRANCH TELLOR ACCOUNT',
                'verbose_name_plural': 'BRANCH TELLOR ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBranchTellorAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('CyCode', models.CharField(max_length=5)),
                ('CyDesc', models.CharField(max_length=10)),
                ('MainCode', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical BRANCH TELLOR ACCOUNT',
                'verbose_name_plural': 'historical BRANCH TELLOR ACCOUNT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
